---
# download src url
download_url:
  ubuntu: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64-disk-kvm.img
  rocky: http://dl.rockylinux.org/vault/rocky/8.5/images/Rocky-8-GenericCloud-8.5-20211114.2.x86_64.qcow2

# download base path
download_path: /data/iso

# src vm image type
src_vm_image_type: ubuntu

# dest vm config
vcpu: 16
memory: 32768

# vm data dir
vmdata_dir: /data/vms

# dest image size
image_size: 60G

# extra disk config
extra_disk_args:

# timezone
timezone: Asia/Seoul

# dns server ip
dns_server: 8.8.8.8

# default user id
default_user: cloud
# root & default password
default_password: cloud2022!

# network config
default_libvirt_network: bridged-network
default_gateway: 192.168.0.1
default_subnet_bit: 16
default_ip: "{{ ansible_host }}/{{ default_subnet_bit }}"

# extra network config
extra_network_args:

# ssh key array
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDvETqvZCNWHPZGMvtL/uMY9gopcKid8VZBZxLfSc74MAOLUbaTM0fMEfBoNQ6jS5A0sQRQTRSDsol7q5Vgnd7/euOJb3CO4O+sXmOL5afG7oBFsyC29Bi3wI1Ao8VaOokc+P04YDdfu0S+Fpi1ZEABwxqOteR15j1ExslquaXn4oPT0ZnH37iT6gepryzQ6W4LHy2oRye9aAKyn4DZnh5hMcY1a1UtocQus5sjWalWVIFHL2Ilt+YYUlIhj1ExSgVrhEQIitbESmrZ+Y4Q+XusaATqdXY8EgifzwrhhykjW9g9WQcv4LBXGBVtvnu7ULNgXsxH9Qu4JDInJ0+JvebD jdlee@laptop-jdlee

