---
- name: Create ssh client config directory
  file:
    path: ${HOME}/.ssh
    state: directory
    recurse: yes

- name: Create ssh key
  openssh_keypair:
    path: ${HOME}/.ssh/id_rsa
    type: rsa
    size: 2048

- name: Get ssh pub key
  command: cat ${HOME}/.ssh/id_rsa.pub
  register: pubkey

- name: Auth add
  set_fact:
    ssh_authorized_keys: "{{ ssh_authorized_keys | default([]) + pubkey.stdout_lines | list }}"

- name: Create ssh client config file
  file:
    path: ${HOME}/.ssh/config
    state: touch
  register: config_exist

- name: Replace ssh client config
  replace:
    path: ${HOME}/.ssh/config
    regexp: '^Host *[\s\S]*^[\s].*'
    replace: |+
      Host *
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null

      # replaced by ansible playbook
  register: ssh_config
  when: config_exist.changed

- name: Create ssh client config
  lineinfile:
    dest: ${HOME}/.ssh/config
    line: |+
      Host *
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null

      # created by ansible playbook
    state: present
  when: not ssh_config.changed

