---
- name: Create image download directory
  file:
    path: "{{ download_path }}"
    state: directory
    recurse: yes

- name: Check image exists
  stat:
    path: "{{ download_path }}/{{ item.value | basename }}"
  register: image_stat
  with_dict: "{{ download_url }}"

- name: Download images
  get_url:
    url: "{{ download_url[item.key] }}"
    dest: "{{ download_path }}/{{ download_url[item.key] | basename }}"
  with_dict: "{{ download_url }}"
  when:
    - not (image_stat.results | selectattr('item.key', 'eq', item.key) | map(attribute='stat.exists') | join('') | bool)
    - not skip_download

