---
- name: KVM server setup
  hosts: kvm_server
  gather_facts: false
  roles:
    - { role: kvm-server }
  tags:
    - kvm

- name: Delete old VM
  hosts: kvm_server
  gather_facts: false
  roles:
    - { role: delete-vm }
  tags:
    - delete

- name: Download cloud images
  hosts: kvm_server
  gather_facts: false
  roles:
    - { role: download }
  tags:
    - download

- name: Create VM
  hosts: kvm_server
  gather_facts: false
  roles:
    - { role: create-vm }
  tags:
    - create

